language: python

python:
  - "2.6"
  - "2.7"

install:
  - pip install -e .
  - pip install -r requirements.txt

script: coverage run tests/test_janitor.py

branches:
  only:
    - master

after_success:
    coveralls
